export const ADD_QUESTIONS = 'ADD_QUESTIONS'
export const QUESTIONS_LOADING_STATUS = 'QUESTIONS_LOADING_STATUS'
export const QUESTIONS_NOMORE_STATUS = 'QUESTIONS_NOMORE_STATUS'
export const ADD_NEW_QUESTIONS_LIST = 'ADD_NEW_QUESTIONS_LIST'
